#导航栏
menu:
  Home: /
  Archive: /archives
  About: /about
  Link: /link

# 关键字
keywords: 

# 站点微缩图
favicon: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png

# 站点 Logo
logo: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png

#css 样式表路径
stylesheets:
- https://cdn.jsdelivr.net/gh/theme-next/theme-next-gitment@1/default.css
- /css/highlight.css
- /css/xc.css

#javascript 脚本路径
scripts:
- https://cdn.jsdelivr.net/gh/theme-next/theme-next-gitment@1/gitment.browser.js
- https://cdn.bootcdn.net/ajax/libs/instantclick/3.1.0/instantclick.min.js
- /js/xc.js

#gitment
gitment:
  owner: wxc0914
  repo: wxc0914.github.io
  client_id: ae41235d0a57566c82de
  client_secret: f34454844f91f4688db6465de3fd8596296e8e52
  cleanly: false //是否隐藏'Powered by Gitment'字样
  language: zh-Hans