#导航栏
menu:
  Home: /
  Archive: /archives
  About: /about
  Link: /link

# 站点微缩图
favicon: "https://github.githubassets.com/images/icons/emoji/unicode/1f34b.png"

# 博主头像
avator: https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png

#css 样式表路径
stylesheets:
- https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
- /css/highlight.css
- /css/xc.css

#javascript 脚本路径
scripts:
- https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js
- https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
- https://cdn.bootcdn.net/ajax/libs/instantclick/3.1.0/instantclick.min.js
- /js/xc.js

#gitalk 相关配置
gitalk:
  owner: wxc0914
  repo: wxc0914.github.io
  client_id: ae41235d0a57566c82de
  client_secret: a7b289897f5919fdcfa747ef84ed66bdf5be49ef

#搜索相关
jsonContent:
  meta:             false
  keywords:         false
  dateFormat:       'YYYY年MM月DD日'
  pages:            false
  posts:
    title:          true
    slug:           false
    date:           true
    updated:        false
    comments:       false
    path:           true
    link:           false
    permalink:      false
    excerpt:        false
    keywords:       false
    text:           true
    raw:            false
    content:        false
    categories:     true
    tags:           true

#seo相关
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true
  content_limit:
  content_limit_delim: ' '

sitemap:
  path: sitemap.xml